<?php

namespace AppBundle\Repository;

/**
 * PlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPlacesList($offset, $limit, $sort){
        $qb = $this->createQueryBuilder('p');

        if(!empty($offset)){
            $qb->setFirstResult($offset);
        }
        if(!empty($limit)){
            $qb->setMaxResults($limit);
        }
        if(in_array($sort, ['asc', 'desc'])){
            $qb->orderBy('p.name', $sort);
        }
        return $qb->getQuery()->getResult();
    }

}
